# Site settings
title: "Şükrü Ozan, Ph.D."
description: "Resume page of Şükrü Ozan"

# List of themes for JSON Resume
json_resume_themes:
  - kendall
  - flat
  - elegant
  - modern

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Şükrü Ozan, Ph.D."
resume_title:                   '("DL/ML Engineer @ digiMOST GmbH","Co-Founder @ AdresGezgini Inc. & CallTech Inc.")'

# used for the contact button in _layouts/resume.html
resume_contact_email:           "sukruozan@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"



resume_header_intro: "<p>As the Co-Founder and Chief Technology Officer (CTO) of CallTech Inc., I lead the development of AI-powered solutions for call center optimization, including speech analytics, sentiment analysis, and performance evaluation. CallTech’s flagship platform, Calltech.app, is a cloud-based system designed to enhance customer satisfaction and improve workflow efficiency for businesses of all sizes. Previously, as the R&D Center Director at AdresGezgini Inc., I oversaw digital marketing solutions and web-based software development projects, working with a team of certified professionals to deliver cutting-edge services to thousands of businesses. I also hold a Ph.D. in Electrical and Electronics Engineering from the İzmir Institute of Technology, where I served as a Research Assistant from 2004 to 2011. In addition, I wasa visiting lecturer at local universities, teaching courses in Image Processing and Python programming. Currently, I also work as a Deep Learning/Machine Learning Engineer at digiMOST GmbH, a subsidiary of AdresGezgini Inc., located in Marl, Germany.Outside of work, I am a father of two and a lifelong learner, continually exploring advancements in AI and technology.</p>"



# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_experience:      true
resume_section_publications:    true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_jsonr_url:             "https://registry.jsonresume.org/sukruozan?theme=kendall"
  resume_gs_url:                "https://scholar.google.com/citations?user=M3vMfZgAAAAJ&hl=en"
  resume_github_url:            "https://github.com/sukruozan"
  resume_twitter_url:           "http://twitter.com/sukruozan"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/sukruozan"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://registry.jsonresume.org/sukruozan"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
